### ISSUE TITLE
Need to create test servers (on SoftLayer)

### ISSUE THREAD

**Issue by ksh0430** [sdevopsadm/roadmap#13]
4 virtual servers are required for production deployment.
    CPU, RAM: Minimum (1 core / 1G)
    IP: 1 public

**Comment by jgkong** [comment]
Purpose of 4 servers are production servers of following spring-petclinic-microservices:
- api-gateway
- customer-services
- vets-services
- visits-services

**Comment by ksh0430** [comment]
이슈로는 서버 주소만 공유드립니다. 
비밀번호는 따로 요청하시는 분께 드리겠습니다.

testvm01.iscloud.co.kr(Virtual Server/Dallas 13)
169.48.71.211 / 10.186.139.88
root / ********

testvm02.iscloud.co.kr(Virtual Server/Dallas 13)
169.48.71.217 / 10.186.139.69
root / ********
  
testvm03.iscloud.co.kr(Virtual Server/Dallas 13)
169.48.71.214 / 10.186.139.110
root / ********

testvm04.iscloud.co.kr(Virtual Server/Dallas 13)
169.48.71.213 / 10.186.139.101
root / ********

**Comment by ksh0430** [comment]
위 4개 가상서버 접속정보는 현재 공진기 차장님과 저(김송현)에게 있습니다.
(비밀번호 or 키파일)
필요하신 분은 요청해주세요.

**Comment by jgkong** [comment]
Can you assign these A DNS records for this servers?
- api-gateway.iscloud.co.kr 169.48.71.211
- customers-service.iscloud.co.kr 169.48.71.213
- vets-service.iscloud.co.kr 169.48.71.214
- visits-service.iscloud.co.kr 169.48.71.217

**Comment by sdevopsadm** [comment]
It's done.
