### ISSUE TITLE
Test servers need to be created

### ISSUE THREAD

**Issue by jgkong** [sdevopsadm/roadmap#2]
4 virtual servers are required for production deployment.
- CPU, RAM: Minimum (1 core / 1G)
- IP: 1 public

**Comment by ksh0430** [comment]
4개 Virtual Machine 생성 완료했습니다.
IP주소는 아래와 같습니다.
  52.62.137.113
  52.64.162.251
  52.64.174.80
  52.64.82.51
접속 정보는 일단 이메일로 다시 드리겠습니다.

**Comment by ksh0430** [comment]
위 VM 4개는 모두 Terminated 처리했습니다.
현재 접속/사용 불가 합니다.
